### ISSUE TITLE
Compatible Sf5 ?

### ISSUE THREAD

**Issue by xorgxx** [rmznpydn/pd-user#3]
Hi it since to be not bad this bundle. is it compatible 100% whit Symfony5 ?

Regards

**Comment by cesurapp** [comment]
I haven't tested it yet.

**Comment by xorgxx** [comment]
ok thank so i will wait for.

**Comment by n-tsvetkov-krez** [comment]
Symfony 5.1.2 Seems working OK. Thanks!
