### ISSUE TITLE
On event how to set in profile?

### ISSUE THREAD

**Issue by xorgxx** [rmznpydn/pd-user#9]
Hi i'm trying to set compagny, and some of my entity profile, in event 
```
        public function onRegisterBefore( UserEvent $userEvent)
        {
            $user = $userEvent->getUser();
            $user->getProfile()->setAddress("dede");
            $user->getProfile()->setCompagny("dede");
        }
```
i get error ```Call to a member function setAddress() on null```
i want to set this form value how was get by api before registration and set in the session.

how do i can do this?

**Comment by cesurapp** [comment]
You may receive an error because the User's Profile has not been created yet.

**Comment by cesurapp** [comment]
$profile = new Profile();
$profile->setAddress('dede')

$user->setProfile($profile);

Try this.

**Comment by xorgxx** [comment]
i will try tomorrow thank's

**Comment by xorgxx** [comment]
it's functional as you ask to do.
